# Your website URL
# Used for sitemap and RSS feed
url: https://hellotunmbi.github.io
title: Tunmbi
description: >
  Frontend Developer | PHP Enthusiast | ES6 | Angular | Everything else inbetween

# Gem-based theme
theme: minima

# Minima settings
# See https://github.com/jekyll/minima/blob/master/README.md
email: hellotunmbi@gmail.com
twitter_username: hellotunmbi
github_username:  hellotunmbi
google_analytics: UA-100697619-1
# Main navigation menu links
header_pages:
 - about.md

# Seo-tag settings
# See https://jekyll.github.io/jekyll-seo-tag/
author: hellotunmbi
twitter:
  username: hellotunmbi

# Gem plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Exclude these files from production
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
