# Site settings
title: "Tunmbi Banto"
email: hellotunmbi@gmail.com
description: "Full Stack Web Developer and Tech Business"
baseurl: ""
url: "http://hellotunmbi.me"
title_description: "Hi.<br/><br/>
My name is <strong>Olutunmbi Banto</strong>.
I am a <strong>Full Stack Web Developer</strong>, always on a journey of constantly learning new things -its an addiction. I enjoy building for the web - mostly.<br/><br/>
Currently, I focus more on building interactive and responsive websites by writing <strong>HTML5, CSS3, Javascript, Angular 2, React and React Native</strong>.<br/><br/>
Started out my coding journey learning <strong>Java (SE and EE)</strong>, moved on to <strong>PHP</strong> because of its simplicity and powerful backend functionalities. Then decided to learn how the frontend works - its <em>simple complexity</em>. I code plain PHP and also use frameworks like <strong>Codeigniter</strong> and <strong>Laravel</strong><br/><br/>"
title_image: "http://res.cloudinary.com/domymi7op/image/upload/c_crop,g_face,w_1463,x_423,y_113/v1509486200/me_background_p6ieel.jpg"
google_analytics: "UA-109565943-1"
disqus_account: hellotunmbi
github_repository: https://github.com/hellotunmbi/
addthis_id:
post_limit: 5

# Social usernames/URLs
twitter_username: hellotunmbi
github_username:  hellotunmbi
instagram_username:
reddit_username:
linkedin_link: https://linkedin.com/in/hellotunmbi
stackoverflow_link:
xing_link:
facebook_link:
medium_link: https://medium.com/@hellotunmbi

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/hellotunmbi/hellotunmbi.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
